;;;; DO NOT MODIFY ;;;;
;;; WARNING ;;;

;; This class was auto-generated by expose-api, do not manually edit
;; or your edits might get overwritten when it gets re-generated.
;; Instead modify the expose-api generation.
;; Refer to https://github.com/xadecimal/expose-api

;;; WARNING ;;;
;;;; DO NOT MODIFY ;;;

(ns com.xadecimal.async-style
  "Async/await-style concurrency and async iteration built on core.async.

Choosing an execution:
    async: an IOC core.async go block for async control flow, await, polling, and short non-blocking work; it does not use virtual threads
    blocking: core.async io-thread where available; current core.async uses a virtual thread on Java 21+ and cached platform threads otherwise
    compute: Clojure's fixed Agent pool for heavy or long-running CPU work; do not block, park, or wait
    Executor implementations may vary with the core.async version, JVM capabilities, and executor customization.

Core terms:
    settle(d): deliver one result and close the channel; settling nil closes without delivering because core.async channels cannot contain nil
    fulfill(ed): deliver a value without closing the channel, leaving it open for additional values
    promise-chan: a single-result core.async channel used for async-style execution results and cooperative cancellation
    producer settlement: async, blocking, and compute wait for one returned promise-like single-result value before settling their own result; returned multi-value source channels remain channel values
    ownership: starting async, blocking, or compute inside a running execution creates an owned child unless started inside detach; ending the parent cancels unfinished owned children
    observation: awaiting or composing already-started work borrows it without transferring ownership or cancelling it
    async source: async-generator returns a cold, lifecycle-aware multi-value channel; consumption starts its producer in the consuming scope, and channel close or a nil take means done"
  (:refer-clojure :exclude [areduce await time])
  (:require [com.xadecimal.async-style.impl :as impl]
            [com.xadecimal.async-style.protocols :as proto]))

(defn error?
  "Returns true if v is considered an error as per async-style's error
   representations, false otherwise. Valid error representations in async-style
   for now are:
     * instances of Throwable"
  {:inline (fn ([v] ` (com.xadecimal.async-style.impl/error? ~v)))}
  ([v] (com.xadecimal.async-style.impl/error? v)))

(defn ok?
  "Returns true if v is not considered an error as per async-style's error
   representations, false otherwise. Valid error representations in async-style
   for now are:
     * instances of Throwable"
  {:inline (fn ([v] ` (com.xadecimal.async-style.impl/ok? ~v)))}
  ([v] (com.xadecimal.async-style.impl/ok? v)))

(defn cancelled?
  "Returns true if execution context was cancelled and thus should be
   interrupted/short-circuited, false otherwise.

   Users are expected, when inside an execution block like async, blocking or
   compute, to check using (cancelled? or check-cancelled!) as often as they can
   in case someone tried to cancel their execution, in which case they should
   interrupt/short-circuit the work as soon as they can."
  {:inline (fn ([] ` (com.xadecimal.async-style.impl/cancelled?)))}
  ([] (com.xadecimal.async-style.impl/cancelled?)))

(defn check-cancelled!
  "Throws if execution context was cancelled and thus should be
   interrupted/short-circuited, returns nil.

   Users are expected, when inside an execution block like async, blocking or
   compute, to check using (cancelled? or check-cancelled!) as often as they can
   in case someone tried to cancel their execution, in which case they should
   interrupt/short-circuit the work as soon as they can."
  {:inline (fn ([] ` (com.xadecimal.async-style.impl/check-cancelled!)))}
  ([] (com.xadecimal.async-style.impl/check-cancelled!)))

(defn cancel!
  "When called on chan, tries to tell processes currently executing over the
   chan that they should interrupt and short-circuit (aka cancel) their execution
   as soon as they can, as it is no longer needed.

   The way cancellation is conveyed is by settling the return channel of async,
   blocking and compute blocks to a CancellationException, unless passed a v
   explicitly, in which case it will settle it with v.

   When called on a lifecycle-aware async-style source, such as an
   async-generator, it requests lifecycle cleanup using the same path as areturn.
   This is fire-and-forget; use areturn when you need to wait for cleanup and
   finally blocks to finish.

   That means by default a block that has its execution cancelled will return a
   CancellationException and thus awaiters and other takers of its result will
   see the exception and can handle it accordingly. If instead you want to cancel
   the block so it returns a value, pass in a v and the awaiters and takers will
   receive that value instead. You can't set nil as the cancelled value,
   attempting to do so will throw an IllegalArgumentException.

   It is up to processes inside async, blocking and compute blocks to properly
   check for cancellation on a channel."
  {:inline (fn
             ([chan] ` (com.xadecimal.async-style.impl/cancel! ~chan))
             ([chan v] ` (com.xadecimal.async-style.impl/cancel! ~chan ~v)))}
  ([chan] (com.xadecimal.async-style.impl/cancel! chan))
  ([chan v] (com.xadecimal.async-style.impl/cancel! chan v)))

(defmacro detach
  "Runs body outside the current cancellation context.

   Use when spawning work that should not be cancelled when the parent is
   cancelled or completed (fire-and-forget, background work, etc.):

     (async
       (let [background (detach (async ...))]  ; won't be cancelled with parent
         ...))

   Can also be used around await*/wait* to prevent reading the parent's
   cancellation channel."
  {}
  ([& body] ` (com.xadecimal.async-style.impl/detach ~@body)))

(defn ->promise-chan
  "Coerce to a promise-chan if possible, otherwise is just a pass-through.

     Currently supports:
       * Future
       * CompletableFuture
       * IBlockingDeref"
  {:inline
     (fn ([this] ` (com.xadecimal.async-style.protocols/->promise-chan ~this)))}
  ([this] (com.xadecimal.async-style.protocols/->promise-chan this)))

(defmacro await*
  "Parking takes from chan-or-value so that any exception is returned, and with
   async-style promise values settled by their producers.

   Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {}
  ([chan-or-value] ` (com.xadecimal.async-style.impl/await* ~chan-or-value)))

(defn wait*
  "Blocking takes from chan-or-value so that any exception is returned, and with
   async-style promise values settled by their producers.

   Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {:inline (fn
             ([chan-or-value]
              `
              (com.xadecimal.async-style.impl/wait* ~chan-or-value)))}
  ([chan-or-value] (com.xadecimal.async-style.impl/wait* chan-or-value)))

(defmacro async
  "Asynchronously execute body as a core.async go block with support for
   cancellation, returning a promise-chan settled with the result or any
   exception thrown.

   Use async for async control flow, parking with await, polling, and short
   non-blocking work. Do not perform blocking I/O, blocking waits, or sustained
   CPU-heavy work; use blocking or compute instead. Async remains an IOC go
   block and does not switch to virtual-thread execution when virtual threads
   are available.

   A leading options map followed by body forms is reserved for future use and
   must currently be empty. A sole map remains an ordinary body value."
  {}
  ([& body] ` (com.xadecimal.async-style.impl/async ~@body)))

(defmacro blocking
  "Asynchronously execute body in the blocking execution context with support
   for cancellation, returning a promise-chan settled with the result or any
   exception thrown.

   Uses core.async io-thread when available and falls back to core.async thread
   on older versions. Current core.async uses one virtual thread per io-thread
   task on Java 21+, with cached platform threads as the fallback. Use blocking
   for blocking I/O, sleeps, and blocking waits, not sustained CPU-heavy work.
   Cancellation interrupts the worker but remains cooperative for code that
   ignores interruption.

   A leading options map followed by body forms is reserved for future use and
   must currently be empty. A sole map remains an ordinary body value."
  {}
  ([& body] ` (com.xadecimal.async-style.impl/blocking ~@body)))

(defmacro compute
  "Asynchronously execute body on Clojure's fixed Agent pooled executor with
   support for cancellation, returning a promise-chan settled with the result
   or any exception thrown.

   The executor uses the available processor count plus two platform threads.
   Use compute for heavy or long-running CPU work. Do not block, park, or wait;
   use blocking for blocking operations and async for short orchestration work.

   A leading options map followed by body forms is reserved for future use and
   must currently be empty. A sole map remains an ordinary body value."
  {}
  ([& body] ` (com.xadecimal.async-style.impl/compute ~@body)))

(defmacro await
  "Parking takes from chan-or-value so that any exception taken is re-thrown,
   returning the value settled by the producer.

   Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {}
  ([chan-or-value] ` (com.xadecimal.async-style.impl/await ~chan-or-value)))

(defmacro wait
  "Blocking takes from chan-or-value so that any exception taken is re-thrown,
   returning the value settled by the producer.

   Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {}
  ([chan-or-value] ` (com.xadecimal.async-style.impl/wait ~chan-or-value)))

(defn catch
  "Parking takes the settled value from chan. If value is an error of
   pred-or-type, will call error-handler with it.

   Returns a promise-chan settled with the value or the return of the
   error-handler.

   error-handler will run in the async execution context, so if you plan on doing something
   blocking or compute heavy, remember to wrap it in a blocking or compute
   respectively.

   Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {:inline (fn
             ([chan error-handler]
              `
              (com.xadecimal.async-style.impl/catch ~chan ~error-handler))
             ([chan pred-or-type error-handler]
              `
              (com.xadecimal.async-style.impl/catch ~chan ~pred-or-type
                ~error-handler)))}
  ([chan error-handler]
   (com.xadecimal.async-style.impl/catch chan error-handler))
  ([chan pred-or-type error-handler]
   (com.xadecimal.async-style.impl/catch chan pred-or-type error-handler)))

(defn finally
  "Parking takes the settled value from chan, and calls f with it no matter if
   the value is ok? or error?.

   Returns a promise-chan settled with the taken value, and not the return of f,
   which means f is implied to be doing side-effect(s).

   f will run in the async execution context, so if you plan on doing something blocking or
   compute heavy, remember to wrap it in a blocking or compute respectively.

   Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {:inline (fn ([chan f] ` (com.xadecimal.async-style.impl/finally ~chan ~f)))}
  ([chan f] (com.xadecimal.async-style.impl/finally chan f)))

(defn then
  "Asynchronously executes f with the result of chan once available, unless chan
   results in an error, in which case f is not executed.

   Returns a promise-chan settled with the result of f or the error.

   f will run in the async execution context, so if you plan on doing something blocking or
   compute heavy, remember to wrap it in a blocking or compute respectively.

   Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {:inline (fn ([chan f] ` (com.xadecimal.async-style.impl/then ~chan ~f)))}
  ([chan f] (com.xadecimal.async-style.impl/then chan f)))

(defn chain
  "Chains multiple then together starting with chan like:
     (-> chan (then f1) (then f2) (then fs) ...)

   fs will all run in the async execution context, so if you plan on doing something blocking
   or compute heavy, remember to wrap it in a blocking or compute respectively.

   Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {:inline (fn
             ([chan & fs] ` (com.xadecimal.async-style.impl/chain ~chan ~@fs)))}
  ([chan & fs]
   (clojure.core/apply com.xadecimal.async-style.impl/chain chan fs)))

(defn handle
  "Asynchronously executes f with the result of chan once available (f result),
   unlike then, handle will always execute f, when chan's result is an error f is
   called with the error (f error).

   Returns a promise-chan settled with the result of f.

   Alternatively, one can pass an ok-handler and an error-handler and the
   respective one will be called based on if chan's result is ok (ok-handler
   result) or an error (error-handler error).

   f, ok-handler and error-handler will all run in the async execution context, so if you
   plan on doing something blocking or compute heavy, remember to wrap it in a
   blocking or compute respectively.

   Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {:inline (fn
             ([chan f] ` (com.xadecimal.async-style.impl/handle ~chan ~f))
             ([chan ok-handler error-handler]
              `
              (com.xadecimal.async-style.impl/handle ~chan
                                                     ~ok-handler
                                                     ~error-handler)))}
  ([chan f] (com.xadecimal.async-style.impl/handle chan f))
  ([chan ok-handler error-handler]
   (com.xadecimal.async-style.impl/handle chan ok-handler error-handler)))

(defn sleep
  "Asynchronously sleep ms time, returns a promise-chan which settles after ms
   time."
  {:inline (fn ([ms] ` (com.xadecimal.async-style.impl/sleep ~ms)))}
  ([ms] (com.xadecimal.async-style.impl/sleep ms)))

(defn defer
  "Waits ms time and then asynchronously executes value-or-fn, returning a
   promsie-chan settled with the result.

   value-or-fn will run in the async execution context, so if you plan on doing something
   blocking or compute heavy, remember to wrap it in a blocking or compute
   respectively."
  {:inline (fn
             ([ms value-or-fn]
              `
              (com.xadecimal.async-style.impl/defer ~ms ~value-or-fn)))}
  ([ms value-or-fn] (com.xadecimal.async-style.impl/defer ms value-or-fn)))

(defn timeout
  "Observes one result from chan before ms time has passed and returns a
   promise-chan settled with that result. If the deadline wins, returns a
   promise-chan settled with a TimeoutException or the result of
   timed-out-value-or-fn.

   Timing out only stops timeout's own observation. It does not close, cancel,
   or lifecycle-return chan, so a many-valued channel remains usable.

   timed-out-value-or-fn will run in the async execution context, so if you plan on doing
   something blocking or compute heavy, remember to wrap it in a blocking or
   compute respectively.

   Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {:inline (fn
             ([chan ms] ` (com.xadecimal.async-style.impl/timeout ~chan ~ms))
             ([chan ms timed-out-value-or-fn]
              `
              (com.xadecimal.async-style.impl/timeout ~chan
                                                      ~ms
                                                      ~timed-out-value-or-fn)))}
  ([chan ms] (com.xadecimal.async-style.impl/timeout chan ms))
  ([chan ms timed-out-value-or-fn]
   (com.xadecimal.async-style.impl/timeout chan ms timed-out-value-or-fn)))

(defn race
  "Returns a promise-chan that settles with the first observed result from
   chans. A many-valued channel contributes one next take, and a single shared
   selection ensures losing many-valued channels are not consumed.

   Unlike any, this will also return the first error? to be returned by one of
   the chans. So if the first chan to fulfill does so with an error?, race will
   return a promise-chan settled with that error.

   Inputs are observed only; race does not close, cancel, or lifecycle-return
   them.

  Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {:inline (fn ([chans] ` (com.xadecimal.async-style.impl/race ~chans)))}
  ([chans] (com.xadecimal.async-style.impl/race chans)))

(defn any
  "Returns a promise-chan that settles as soon as one of the chan in chans
   fulfills in ok?, with the value settled by that chan.

   Unlike race, this will ignore chans that fulfilled with an error?. So if the
   first chan to fulfill does so with an error?, any will keep waiting for
   another chan to eventually fulfill in ok?.

   If all chans fulfill in error?, returns an error containing the list of all
   the errors.

   Each many-valued channel contributes at most one next take. Inputs are
   observed only; any does not close, cancel, or lifecycle-return them.

  Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {:inline (fn ([chans] ` (com.xadecimal.async-style.impl/any ~chans)))}
  ([chans] (com.xadecimal.async-style.impl/any chans)))

(defn all-settled
  "Concurrently observes one result from each input in chans and returns a
   promise-chan settled with a vector of the ok? and error? results in input
   order. Many-valued channels contribute one next take.

   It is typically used when you have multiple asynchronous tasks that are not
   dependent on one another to complete successfully, or you'd always like to
   know the result of each chan even when one errors.

   In comparison, the promise-chan returned by all may be more appropriate if
   the tasks are dependent on each other / if you'd like to immediately stop upon
   any of them returning an error?.

   Inputs are observed only; all-settled does not close, cancel, or
   lifecycle-return them.

  Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {:inline (fn ([chans] ` (com.xadecimal.async-style.impl/all-settled ~chans)))}
  ([chans] (com.xadecimal.async-style.impl/all-settled chans)))

(defn all
  "Takes a seqable of chans as an input, and returns a promise-chan that settles
   after all of the given chans have fulfilled in ok?, with a vector of the taken
   ok? results of the input chans. This returned promise-chan will settle when
   all of the input's chans have fulfilled, or if the input seqable contains no
   chans (only values or empty). It settles in error? immediately upon any of the
   input chans returning an error? or non-chans throwing an error?, and will
   contain the error? of the first taken chan to return one.

   Inputs are observed concurrently and many-valued channels contribute one
   next take. All does not close, cancel, or lifecycle-return inputs when one
   errors.

  Note:
    * chan can be a channel or something supported by IntoPromiseChan."
  {:inline (fn ([chans] ` (com.xadecimal.async-style.impl/all ~chans)))}
  ([chans] (com.xadecimal.async-style.impl/all chans)))

(defmacro async-generator
  "Creates a cold async-style channel whose body can yield many values.

   The body runs in an async go-block context when the returned channel is first consumed,
   not when the channel is created. Values published with yield are delivered as
   raw channel values, and channel close means the generator is done.

   Accepts an optional options map. Currently supported:
     * :buffer-size - fixed, lossless output buffer size. Defaults to 0 for an
       unbuffered, pull-based handoff."
  {}
  ([& body] ` (com.xadecimal.async-style.impl/async-generator ~@body)))

(defmacro yield
  "Publishes one value from inside async-generator.

   The value is consumed through await before it is put on the output channel, so
   yielding a promise-chan, Future, or CompletableFuture exposes its settled
   value to downstream consumers. yield parks when the configured generator
   buffer is full and returns nil on success.

   async-generator cannot yield nil, because nil is core.async's closed-channel
   value and means the source is done."
  {}
  ([v] ` (com.xadecimal.async-style.impl/yield ~v)))

(defn anext
  "Takes one raw value from channel-like source, returning a promise-chan.

   If source is a cold async-style generator, taking starts it in the current
   scope. The returned promise-chan settles to the next value, or nil when the
   source is done. Errors are represented using normal async-style semantics:
   use wait/await to throw them, or wait*/await* to receive them as values.

   anext observes borrowed plain channels without closing or cancelling them.
   Collection-like sources are not supported."
  {:inline (fn ([source] ` (com.xadecimal.async-style.impl/anext ~source)))}
  ([source] (com.xadecimal.async-style.impl/anext source)))

(defn areturn
  "Requests early cleanup for a lifecycle-aware async-style source.

   Returns a promise-chan settling to nil after cleanup has completed. For
   borrowed plain channels, areturn is a no-op: it does not close or cancel the
   channel."
  {:inline (fn ([source] ` (com.xadecimal.async-style.impl/areturn ~source)))}
  ([source] (com.xadecimal.async-style.impl/areturn source)))

(defmacro adoseq
  "Asynchronously consumes channel-like or collection-like sources for side
   effects, returning a promise-chan that settles to nil.

   Binding forms follow Clojure doseq/for style for destructuring, nested
   bindings, :let, :when, and :while. Each element is consumed with await
   semantics. On :while short-circuit, errors, or cancellation,
   lifecycle-aware sources are returned/cleaned up; borrowed plain channels are
   only observed."
  {}
  ([bindings & body]
   `
   (com.xadecimal.async-style.impl/adoseq ~bindings ~@body)))

(defmacro afor
  "Asynchronously comprehends over channel-like or collection-like sources,
   returning a promise-chan settled with an eager vector of body results.

   Supports the same binding and qualifier forms as adoseq. Body-returned
   reduced values are ordinary values; use :while for short-circuiting."
  {}
  ([bindings & body] ` (com.xadecimal.async-style.impl/afor ~bindings ~@body)))

(defn areduce
  "Asynchronously reduces source with rf and init, returning a promise-chan
   settled with the final accumulator.

   source may be channel-like or collection-like. Each element is consumed with
   await semantics, so Throwable values are thrown and values supported by
   IntoPromiseChan are awaited. If rf returns reduced, reduction stops early,
   lifecycle-aware sources are returned/cleaned up, and the promise-chan settles
   with the unwrapped reduced value.

   rf runs in the async execution context and should be quick: do not block, park, wait, or
   perform heavy compute work inside it."
  {:inline (fn
             ([rf init source]
              `
              (com.xadecimal.async-style.impl/areduce ~rf ~init ~source)))}
  ([rf init source] (com.xadecimal.async-style.impl/areduce rf init source)))

(defn atransduce
  "Asynchronously transduces source with xf, rf, and init, returning a
   promise-chan settled with the completed reduction result.

   source may be channel-like or collection-like. Early transducer completion,
   errors, and cancellation return/clean up lifecycle-aware sources. Transducer
   and reducing steps run in the async execution context and should be quick; do not block,
   park, wait, or perform heavy compute work inside them."
  {:inline
     (fn
       ([xf rf init source]
        `
        (com.xadecimal.async-style.impl/atransduce ~xf ~rf ~init ~source)))}
  ([xf rf init source]
   (com.xadecimal.async-style.impl/atransduce xf rf init source)))

(defn ainto
  "Asynchronously consumes source into to, returning a promise-chan settled with
   the completed collection.

   With two arguments, behaves like async into. With three arguments, applies xf
   as a transducer. source may be channel-like or collection-like, and each
   element is consumed with await semantics."
  {:inline (fn
             ([to source] ` (com.xadecimal.async-style.impl/ainto ~to ~source))
             ([to xf source]
              `
              (com.xadecimal.async-style.impl/ainto ~to ~xf ~source)))}
  ([to source] (com.xadecimal.async-style.impl/ainto to source))
  ([to xf source] (com.xadecimal.async-style.impl/ainto to xf source)))

(defmacro ado
  "Asynchronous do. Execute expressions one after the other, awaiting the result
   of each one before moving on to the next. Results are lost to the void, same
   as clojure.core/do, so side effects are expected. Returns a promise-chan which
   settles with the result of the last expression when the entire do! is done.

   Note:
    * exprs can return a channel or something supported by IntoPromiseChan."
  {}
  ([& exprs] ` (com.xadecimal.async-style.impl/ado ~@exprs)))

(defmacro alet
  "Asynchronous let. Binds result of async expressions to local binding, executing
   bindings in order one after the other.

   Note:
    * exprs can return a channel or something supported by IntoPromiseChan."
  {}
  ([bindings & exprs]
   `
   (com.xadecimal.async-style.impl/alet ~bindings ~@exprs)))

(defmacro clet
  "Concurrent let. Executes all bound expressions in an async block so that
   the bindings run concurrently. If a later binding or the body depends on an
   earlier binding, that reference is automatically replaced with an await.
   In a blocking/compute context, await is transformed to wait for proper
   blocking behavior.

   Notes:
     * Bindings are evaluated in the async execution context; therefore, they should not
       perform blocking I/O or heavy compute directly. If you need to do blocking
       operations or heavy compute, wrap the binding in a blocking or compute call.
     * This macro only supports simple symbol bindings; destructuring (vector or
       map destructuring) is not supported.
     * It will transform symbols even inside quoted forms, so literal code in quotes
       may be rewritten unexpectedly.
     * Inner local bindings (e.g. via a nested let) that shadow an outer binding are
       not handled separately; the macro will attempt to rewrite every occurrence,
       which may lead to incorrect replacements.
     * Anonymous functions that use parameter names identical to outer bindings
       will also be rewritten, which can cause unintended behavior if they are meant
       to shadow those bindings."
  {}
  ([bindings & body] ` (com.xadecimal.async-style.impl/clet ~bindings ~@body)))

(defmacro time
  "Evaluates expr and reports the time it took. Returns the original value of
   expr. If expr evaluates to a channel, observes one result before reporting.

   The timing callback is detached observation-only instrumentation. It does
   not own or manage the observed value and is not suppressed merely because
   the caller's cancellation scope completes.

   Note:
    * expr can return a channel or something supported by IntoPromiseChan."
  {}
  ([expr] ` (com.xadecimal.async-style.impl/time ~expr))
  ([expr print-fn] ` (com.xadecimal.async-style.impl/time ~expr ~print-fn)))

;;;; DO NOT MODIFY ;;;;
;;; WARNING ;;;

;; This class was auto-generated by expose-api, do not manually edit
;; or your edits might get overwritten when it gets re-generated.
;; Instead modify the expose-api generation.
;; Refer to https://github.com/xadecimal/expose-api

;;; WARNING ;;;
;;;; DO NOT MODIFY ;;;
